title: David Grijalva
logo: "/assets/profile-pic/19814808.jpeg" 
description: > 
  <bold>About:</bold>
  Product Lead with demonstrated experience in exploring data in order to create actionable insights and turning them into impactful results. Strongly passionate about product management, data science, machine learning and natural language processing. 
  <br><br>

  <a href="https://www.linkedin.com/in/david-grijalva/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal